export type HomeScreenStackParamlist = {
  GenreSelector: undefined;
  MovieSwiper: { genres: Genre[] };
};

export type SearchScreenStackParamList = {
  Search: undefined;
  MovieDetails: { movieId: MovieTopDetails["id"] };
};

export type ListScreenStackParamLst = {
  Lists: undefined;
  MovieDetails: { movieId: MovieTopDetails["id"] };
};

export interface Genre {
  id: number;
  name: string;
}

export interface Actor {
  id: number;
  name: string;
  profile_path: string;
  character: string;
  order: number;
}

export interface MovieTopDetails {
  adult: boolean;
  backdrop_path: string;
  belongs_to_collection: string;
  budget: number;
  genres: Genre[];
  homepage: string;
  id: number;
  imdb_id: number;
  original_language: string;
  original_title: string;
  overview: string;
  popularity: number;
  poster_path: string;
  production_companies: Array<{
    id: number;
    logo_path: string;
    name: string;
    origin_country: string;
  }>;
  production_countries: Array<{
    iso_3166_1: string;
    name: string;
  }>;
  release_date: string;
  revenue: number;
  runtime: number;
  spoken_languages: Array<{
    english_name: string;
    iso_639_1: string;
    name: string;
  }>;
  status: string;
  tagline: string;
  title: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
}

export interface MovieSearchResult {
  page: number;
  results: Array<{
    adult: boolean;
    backdrop_path: string;
    genre_ids: Array<Genre["id"]>;
    id: number;
    original_language: string;
    original_title: string;
    overview: string;
    popularity: number;
    poster_path: string;
    release_date: string;
    title: string;
    video: boolean;
    vote_average: number;
    vote_count: number;
  }>;
  total_pages: number;
  total_results: number;
}

export type Movie = MovieSearchResult["results"][number] | MovieTopDetails;

/** Data type of the Movie table stored in SQLite */
export interface LocalMovieData {
  /** ID generated by SQLite */
  id: number;

  /** TMDB ID */
  movie_id: number;

  /** 0 = false, 1 = true */
  has_watched: number;
}
